config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  resources :sessions, only: [:create, :destroy]

  get 'welcome/index'
  
  resources :posts do
    resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'about/index'
  root 'about#index'
  
  get 'team/index'
  root 'team#index'
  
  get 'what/index'
  root 'what#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy 
    validates :title, presence: true, length: {minimum: 5}
    validates :text,  presence: true, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord     
    def self.from_omniauth(auth)         
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider             
            user.uid = auth.uid             
            user.name = auth.info.name             
            user.oauth_token = auth.credentials.token             
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)             
            user.save!         
        end     
    end 
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
end

def destroy 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
end
    
private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
        
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
       @posts = Post.all
    end
    def show
        @post = Post.find(params[:id])
    end
    
    def new
       @post = Post.new
    end
    
    def create
      #render plain: params[:post].inspect
      @post = Post.new(post_params)
        #byebug
       if @post.save 
           #byebug
           redirect_to @post
       else 
           render 'new'
        end
    end
    
    def edit
       @post = Post.find(params[:id])
    end 
    
   def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else 
            render 'edit'
        end
    end 
    
     def destroy
         @post = Post.find(params[:id])
         @post.destroy
        
         redirect_to posts_path
    end
end

private
def post_params
   params.require(:post).permit(:title, :text)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/what_controller.rb
class WhatController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/what_helper.rb
module WhatHelper
end

app/views/about/index.html.erb
<div id="nav">
	<nav>
		<ul>
			<a id="sign_in" href="https://itsc3155rubyprojects-agovor.c9users.io/">Home</a>
			<a id ="sign_in" href="/about/index">About Us</a>
			<a id ="sign_in" href="/team/index">Meet The Team</a>
			<a id ="sign_in" href="/what/index">FAQs</a>
			
			<%= link_to 'Posts', controller: 'posts'%>
				
		</ul>
	</nav>
</div>
<h1>About Us</h1><hr> <p>&nbsp;</p> </hr>
<div id="content"> 
<div id="main"> 
<article id="post-6497" class="post-6497 page type-page status-publish hentry"> 
<div class="post-header"> 
</div> 
    <div class="post-entry"> 
    <p><img class="about" src="http://www.uncc.edu/sites/www.uncc.edu/files/gallery/49erMiner-cropped.jpg" 
    sizes="(max-width: 2000px) 100vw, 700px" width="1000" height="524"></p> 
    <p>Hello viewers! Welcome to the 704 Blog! This blog contains about various news updates and random articles about the UNCC lifestyle and its community.
    Submit a post in the listing post page and as a group we will decide which posts best suit our blog and will be
    published onto our homepage. Our main focus is to provide bloggers with a sense of awarness of what's going on and how YOU can also 
    contribute to this blog!</p>
</div>

<%= link_to 'Back Home', welcome_index_path %>

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>

<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Destroy Comment', [comment.post, comment],
                                    method: :delete,
                                    data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :commenter %><br>
        <%= f.text_field :commenter %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gold</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Log Out" , signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Log In", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
 <p>
    <%= f.submit %>
</p>

 
<% end %>

app/views/posts/edit.html.erb
<h1>Editing posts</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="nav">
	<nav>
		<ul>
			<a id="sign_in" href="https://itsc3155rubyprojects-agovor.c9users.io/">Home</a>
			<a id ="sign_in" href="/about/index">About Us</a>
			<a id ="sign_in" href="/team/index">Meet The Team</a>
			<a id ="sign_in" href="/what/index">FAQs</a>
			
			<%= link_to 'Posts', controller: 'posts'%>
				
		</ul>
	</nav>
</div>
<h1>Listing Posts</h1>
<%= link_to 'New Post', new_post_path %>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    
    <% @posts.each do |post| %>
    <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show' , post_path(post) %></td>
        <td><%= link_to 'Edit' , edit_post_path(post) %></td>
        <td><%= link_to 'Delete', 
                                post_path(post), 
                 
                                method: :delete, 
                                data: { confirm: 'Are you sure?' } %></td>
        
    </tr>
    <% end %>
</table>

<%= link_to 'Back Home', welcome_index_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>Showing Posts</h1>

<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @post.text %>
</p>

<div id="comments">
<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

</div>

<%= link_to 'Post List', posts_path %>

app/views/team/index.html.erb
<div id="nav">
	<nav>
		<ul>
			<a id="sign_in" href="https://itsc3155rubyprojects-agovor.c9users.io/">Home</a>
			<a id ="sign_in" href="/about/index">About Us</a>
			<a id ="sign_in" href="/team/index">Meet The Team</a>
			<a id ="sign_in" href="/what/index">FAQs</a>
			
			<%= link_to 'Posts', controller: 'posts'%>
				
		</ul>
	</nav>
</div>
<h1>Meet the Team</h1><hr> <p>&nbsp;</p> </hr>
<div id="content"> 
<div id="main"> 
<article id="post-6497" class="post-6497 page type-page status-publish hentry"> 
<div class="post-header"> 
    <div class="post-share"> 
        <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http://theswirlblog.com/about/"><i class="fa fa-facebook"></i></a> 
        <a target="_blank" href="https://twitter.com/home?status=Check%20out%20this%20article:%20About &amp; FAQ’s%20-%20http://theswirlblog.com/about/"><i class="fa fa-twitter"></i></a>
        <a class="btnPinIt" href="http://theswirlblog.com/about/" data-image="" data-desc="About &amp; FAQ’s"><i class="fa fa-pinterest"></i></a> 
        <a target="_blank" href="https://plus.google.com/share?url=http://theswirlblog.com/about/"><i class="fa fa-google-plus"></i></a> 
    </div> 
</div> 
    <div class="post-entry"> 
    <p><img class="team" src="https://www.prestashop.com/blog/en/files/2013/11/4041.jpg" 
    sizes="(max-width: 2000px) 100vw, 700px" width="1000" height="524"></p> 
    <p>Hello to all of you bloggers! We are a group based blogger named 404 Not Found. Here are some things you should know about us:</p> 
        <ul> 
            <li>We are innovative, intuitive and amateur bloggers! So we are kind of new at this! Haha. </li> 
            <li>Our group is composed of undergraduate CompSci students from the University of North Carolina at Charlotte.</li> 
            <li>Founded on the beginning of the Spring Semester of 2017.</li>
            <li>Brendon: "Hi, guys! I am currently a rising senior studying Software, Systems, and Networking with a minor in Chinese. I am aspiring to be a software developer as my future career.
            I am the first generation within my family to go to college. UNCC has been one of the best decisions that I have made in my life so far. Go 49ers!"</li> 
            <li>Carrie: "I am rising senior, studying Software Information Systems with a concentration in Cyber Security.
            I love my friends and family. I am so grateful for the opportunities UNCC has provided me. GO NINERS!"</li> 
            <li>Tin: "Hello everyone thanks for checking out the blog. I'm a senior at UNC Charlotte pursing my degree in Computer Science. My hobby is to program, blog, and hang out in Charlotte.
            I am glad I went to UNCC because I met so many friends and the community is Awesome!!</li> 
            <li>Davidson: "Yo what sup everyone. I'm also a Computer Science major. In my free time I like to catch reptiles. UNCC is a great school, being a 49er is the best feeling in the world!
            I've learned so many things and met people who helped me in classes when I needed help."</li> 
        </ul> 
 


<%= link_to 'Back Home', welcome_index_path %>

app/views/welcome/index.html.erb
<div id="nav">
	<nav>
		<ul>
			<a id="sign_in" href="https://itsc3155rubyprojects-agovor.c9users.io/">Home</a>
			<a id ="sign_in" href="/about/index">About Us</a>
			<a id ="sign_in" href="/team/index">Meet The Team</a>
			<a id ="sign_in" href="/what/index">FAQs</a>
			
			<%= link_to 'Posts', controller: 'posts'%>
				
		</ul>
	</nav>
</div>

<header>
<div class="header">
	<center><img src="http://advancement.uncc.edu/sites/advancement.uncc.edu/files/media/athletics-200.fw.png" /> 
	<h1 class="title">WELCOME TO THE 704 BLOG!</h1>
	
</center>

</header>

</div>

<div id="features">
	<div class="wrapper">
		<ul>
			<li class="Daily Tip">
				<h4>Daily Tips</h4>
				<p>Get here early to find a parking space!</p>
			</li>
			
			<li class="New Feature">
				<h4>New Feature</h4>
				<p>STARBUCKS HAS UNICORN FRAPPUCCINOS!!!!!! GO TRY IT OUT!!!!!!</p>
			</li>
			
			<li class="Daiiy Tip">
				<h4>Daily Tips</h4>
				<p>Avoid Crown Commons. Go SoVi for better quality food.</p>
			</li>
			
			<li class="Update">
				<h4>Update</h4>
				<p>UPDATE! The 49er football team won against Pennstate by 18-4 </p>
			</li>
			
			<li class="Daily Tip">
				<h4>Daily Tips</h4>
				<p>Watch for "landmines" during goose season</p>
			</li>
			
			<li class="Update">
				<h4>Update</h4>
				<p>UPDATE! The university will be implementing a new parking system. 
				They will also be removing two parking lots. Specifically Lot 18 and 19. </p>
			</li>
			
			<li class="Daily Tip">
				<h4>Daily Tips</h4>
				<p>Always check for rent-a-puppy on Tuesday and Thursday</p>
			</li>
			
			<li class="Update">
				<h4>Update</h4>
				<p>UPDATE! Campus will be experiencing walnut sized hail and F5 tornadoes storms in the afternoon </p>
			</li>
			
			<div class="clear"></div>
		</ul>
	</div>
</div>

<footer>
	<div class="wrapper">
		<div id="footer-info">
			<p>Copyright 2017 704 Blog. All rights reserved.</p>
			<p><a>Terms of Service</a> <a>Privacy</a></p>
		</div>
		<div id="footer-links">
			<ul>
			
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</footer>

app/views/welcome/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @post.text %>
</p>
<%= link_to 'Post List', posts_path %>

app/views/what/index.html.erb
<div id="nav">
	<nav>
		<ul>
			<a id="sign_in" href="https://itsc3155rubyprojects-agovor.c9users.io/">Home</a>
			<a id ="sign_in" href="/about/index">About Us</a>
			<a id ="sign_in" href="/team/index">Meet The Team</a>
			<a id ="sign_in" href="/what/index">FAQs</a>
			
			<%= link_to 'Posts', controller: 'posts'%>
				
		</ul>
	</nav>
</div>
<h1>FAQs</h1>
<div id="content"> 
<div id="main"> 
<article id="post-6497" class="post-6497 page type-page status-publish hentry"> 
<div class="post-header"> 

  <hr> <p>&nbsp;</p>
        <p><em><strong>Q: What does 404 Not Found mean?</strong></em></p> 
        <p>A: The '404 not found' is an error when a webpage that a person is trying to find could not be reached
        because of an error. Our group thought the error was funny and thought it was a unique name for a group,
        so that is the story of how we became the '404 Not Found' :) </p> 
        <p><em><strong>Q: What do you blog about?</strong></em></p> 
        <p>A: We blog about everything to giving tips, to informing 49ers of future events, to giving updates around the school, 
        and many more information related to all 49ers!</p> 
        <p><em><strong>Q: I love your blog and I want more of The 704! What can I do?</strong></em></p> 
        <p>A: Hello, thanks for supporting our blog!! A few things you or anyone else who want to support the community is to post 
        relevant information or new information that could assist others. </p>
        <p><em><strong>Q: I submitted my post a few days ago, when will it be posted to the homepage?&nbsp;</strong></em></p>
        <p>A: Great! We’re accepting guest posts! It can be on anything that 17-22 year olds would enjoy reading! A lot of our audience are college students and we’d love to get beauty and fashion on our blog too! Send us your drafts/ideas (theghswirl@gmail.com)!</p> 
        </div> 
    <div class="post-meta main_post_meta"> 

    </aside> 
</div>

    </aside> 
</div>


<%= link_to 'Back Home', welcome_index_path %>